// Code generated by mockery v2.42.0. DO NOT EDIT.

package repomocks

import (
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}